# Generated by Django 3.2.6 on 2021-08-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=100)),
                ('client_contact', models.IntegerField(default=0)),
                ('date_published', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
